
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: admin

development:
  <<: *default
  database: booking_slots_development
  socket: /var/run/mysqld/mysqld.sock

test:
  <<: *default
  database: booking_slots_test

production:
  <<: *default
  database: ENV['DATABASE_URL']
  username: ENV['DATABASE_USERNAME']
  password: ENV['DATABASE_PASSWORD']
