
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: admin
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: booking_slots_development

test:
  <<: *default
  database: booking_slots_test

production:
  <<: *default
  database: booking_slots_production
  username: booking_slots
  password: sudha9900
